### ISSUE TITLE
Linting your CSS with StyleLint 👾

### ISSUE THREAD

**Issue by belcherj** [TacoJS/talks#1]
**Your name and twitter handle:**
belcherj

**Your talk idea, described briefly:**
why you should lint your css and how to set it up

**Approx length, must be less than 15 minutes to be considered:**
15 minutes

**Type of talk (creative, passion, technical):**
passion, technical

**Comment by pixelyunicorn** [comment]
Thanks! I've scheduled your talk for the August 25 meetup - see you there!

**Comment by pixelyunicorn** [comment]
Thanks for speaking ❤️
