### ISSUE TITLE
A Better Technical Interview 💚

### ISSUE THREAD

**Issue by samjonester** [TacoJS/talks#11]
**Your name and twitter handle:**
Sam Jones @samjonester

**Your talk idea, described briefly:**

Technical interviews are scary! They often involve pairing, but not the way we do it in real life. Let's discuss a better way to handle technical interviews than playing buzzword bingo and solving algorithms as fast as we can!

This talk presents a better approach to technical interviewing:
* Focus on how to break down problems.
* Prioritize workflow rather than completion.
* Treat it as a chance to see how a candidate learns and teaches in an unfamiliar setting.
* Give positive feedback about what to learn for the next time. Candidates should either be hired or not yet hired.
* Make sure the candidate leaves having learned something from the interview! Don't waste their time even if they're a "not yet".

**Approx length - must be less than 15 minutes to be considered:**
10-15 min

**Type of talk (creative, passion, technical):**
Passion / Softtalk / Noob-love

**Comment by pixelyunicorn** [comment]
Thanks for your talk submission! We only have time for one more talk at our Jan 24th meetup, is there a preference on which talk you wanted to give?

- A Better Technical Interview (tacojs/talks#10)
- A Transformative Pipeline w/ Highland Streams + Lodash FP (tacojs/talks#11)

I (personally) prefer "A Better Technical Interview" to balance out the technical nature of the rest of the 3 other scheduled talks, but that decision is completely up to you.
