### ISSUE TITLE
What is "serverless" even? 👻

### ISSUE THREAD

**Issue by pselle** [TacoJS/talks#2]
**Your name and twitter handle:**
Pam Selle
@pamasaur

**Your talk idea, described briefly:**
The "cloud" is a [mere construct in our minds](https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/3442/large/1418280711/die-cut-stickers.png), but those wild kids are taking things further with "serverless" apps. Now you don't even have an imaginary server – you can run "serverless"!

Serverless is the ~~possible~~ solution to the monolith => microservices => **how do we run all of these things** problem. Using on-demand computation (ex. AWS Lambda), your code no longer lives on a box somewhere, but instead ... lives on a box somewhere **_but_** you only pay for the time it takes to execute. It's pretty neat!

In this talk, you'll learn what is serverless even, what various systems and terms people are talking about, and we'll deploy on on-demand function together, in Node.js bien sûr.

**Approx length, must be less than 15 minutes to be considered:**
10mins

**Type of talk (creative, passion, technical):**
technical

**Comment by pixelyunicorn** [comment]
Thanks! I've scheduled your talk for the August 25 meetup - see you there!

**Comment by pixelyunicorn** [comment]
Thanks for speaking ❤️
