### ISSUE TITLE
Code Tests as Living Documentation 💯

### ISSUE THREAD

**Issue by adccb** [TacoJS/talks#4]
**Your name and twitter handle:**

Logan Crossan
@logan_crossan

**Your talk idea, described briefly:**

I'd like to talk about code testing and how, even if you're not TDDing your code, how important it is to write unit tests. The importance comes two ways -- one, verification that your code works, and two, living documentation that is verifiably true.

**Approx length, must be less than 15 minutes to be considered:**

Around 10 or 15, as long as you'd like!

**Type of talk (creative, passion, technical):**

Passion, probably, with a dash of technical.

**Comment by pixelyunicorn** [comment]
Thanks, Logan! I've scheduled your talk for the October 27 meetup - see you there and let me know if you have any questions! 👍
