### ISSUE TITLE
Realtime Data Visualizations with EON.js 🏀

### ISSUE THREAD

**Issue by elizabethsiegle** [TacoJS/talks#5]
**Your name and twitter handle:**
Lizzie Siegle, @lizziepika

**Your talk idea, described briefly:**

Project EON is an open-sourced, web-based real-time chart/graph data visualization framework that lets you easily customize your visualization with a variety of chart types, themes, markers, and more. The chart builder tool makes it so you may not even have to write a line of code, unless you wanted to really customize your visualization! Realtime data could include weather, stocks, geolocation, or tweets...</li></br>
<li class = "speaker">My project is a realtime data visualization of tweets about the Warriors during the NBA Finals.</li></br>
<li>A quick overview of an iOS app that uses a webview to display heart rate from the Apple Watch. Though EON is a web-based framework, it is easy to use this web-based framework across platforms.</li></br>
<li class ="speaker">Live coding demo on building an NYC sports team data visualization from tweets.

**Approx length, must be less than 15 minutes to be considered:**
12 mins

**Type of talk (creative, passion, technical):**

Creative, technical

**Comment by pixelyunicorn** [comment]
Thanks, Lizzie! I've scheduled your talk for the October 27 meetup - let me know if that date works for you or if you had any questions! 👍

**Comment by elizabethsiegle** [comment]
At the moment, October 27 is good! How many people typically go to TacoJS? Are you looking for company sponsors?

**Comment by pixelyunicorn** [comment]
Awesome, I'll see you on October 27th. We generally have 30 attendees attend TacoJS, and we are always looking for sponsors!

The suggested sponsorship amount is $180. The first $90 cover costs, and any additional sponsorships goes straight to a nonprofit in the area that teaches kids to code. More details here: http://tacojs.rocks/sponsor, let me know if you're interested.

**Comment by elizabethsiegle** [comment]
Wait I'm actually speaking at the CS major tea at school (and want to attend) and just found out it's at the same time--November would be better, then.

**Comment by pixelyunicorn** [comment]
That's fine. We are moving to a bi-monthly schedule (so we don't conflict with the Philly JS meetup), so our next meetup after October would be in early/mid-December

**Comment by notaurologist** [comment]
Sad to see this talk isn't happening this month, but looking forward to it whenever scheduling works out. Will another talk be replacing this one? I held off submitting a PR to the schedule since I don't know how this usually goes.

**Comment by pixelyunicorn** [comment]
@notaurologist Depending on the length of the talks, we have slots for up to 4-6 talks per meetup. Right now only there are currently only 2 talks on the schedule - since @elizabethsiegle can't make it this month it opens up another slot until someone else steps forward and submits a talk or performance.

You can submit anytime you like, even if you can't make it to the next meetup (just indicate so when submitting.)

**Comment by pixelyunicorn** [comment]
@notaurologist Are you still interested in giving a talk next week?

**Comment by notaurologist** [comment]
@LabLayers Sorry for the confusion. No, I don't have a talk right now, but perhaps sometime in the future. I was just curious if the spot had been filled since it was still on the schedule before.

**Comment by LabLayers** [comment]
Our next meetup is happening on Tuesday January 24. Are you able to give your talk on this date?

**Comment by LabLayers** [comment]
@elizabethsiegle Our next meetup is happening on Tuesday January 24. Are you able to give your talk on this date?

**Comment by pixelyunicorn** [comment]
@elizabethsiegle Our next meetup is happening on Tuesday January 24. Are you able to give your talk on this date?

**Comment by elizabethsiegle** [comment]
@LabLayers I don't think so, semester's just starting and it's going to be very hectic :(

**Comment by pixelyunicorn** [comment]
Hey Lizzie, thanks for you talk submission!

Our next TacoJS is on the evening of Tuesday, August 22. Would that date work for you?

**Comment by pixelyunicorn** [comment]
Hey Lizzie (@elizabethsiegle)!

I know it's been a while, but we are looking to start TacoJS back up in the near future. Are you still interested in speaking at the meetup (even if it's on a different topic), and if so, what 3+ months would you be available to speak?

**Comment by elizabethsiegle** [comment]
@pixelyunicorn I am no longer based in Philly so can not speak at a TacoJS in the near future :( Will share with people I think may be interested who are in the area

**Comment by pixelyunicorn** [comment]
Thanks, Lizzie!
