### ISSUE TITLE
Yeoman Generators: How Hard It Could Be? 🎩

### ISSUE THREAD

**Issue by mishgunn** [TacoJS/talks#8]
**Your name and twitter handle:**
Mickael Tardy, @m1ketardy

**Your talk idea, described briefly:**
I would like to talk about yeoman generators and their potential complexity. I would introduce the topic, share my experience with yeoman and allocate some time with audience to learn how others deal with it

**Approx length, must be less than 15 minutes to be considered:**
15min

**Type of talk (creative, passion, technical):**
passion/tech

**Comment by LabLayers** [comment]
Our next meetup is happening on Tuesday January 24. Are you able to give your talk on this date?

**Comment by pixelyunicorn** [comment]
@mishgunn Our next meetup is happening on Tuesday January 24. Are you able to give your talk on this date?

**Comment by mishgunn** [comment]
@LabLayers Sure, unless something really bad happens (-:

**Comment by pixelyunicorn** [comment]
Thanks! I've scheduled your talk for the next TacoJS. See you there!
