### ISSUE TITLE
Isomorphic Clojure Web Apps 🔥

### ISSUE THREAD

**Issue by bhurlow** [TacoJS/talks#9]
Brian Hurlow @bhurlow

I'd like to talk about techniques for developing websites using isomorphic Clojure code – so Clojure(script) that runs on the jvm *and* in the browser sharing as much generic code as possible. This opens up areas lots of interesting possibilities for web applications – server-side rendering of React components, lots more code reuse, hot-reloading, this kind of :fire:. Many people have explored these techniques in js, but less so in the Clojure world.  

15 Minutes 

This would be a technical talk, hopefully practical though :)

**Comment by pixelyunicorn** [comment]
Thanks, Brian! I've scheduled your talk for our next meetup on Jan 24 - let me know if that date works for you or if you have any questions! 👍

**Comment by bhurlow** [comment]
cool! should work, looking forward to it
